
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/377/bin/cmake/linux/x64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.14.0-29-generic - x86_64
...
